#!/usr/bin/env python3

"""ROMS namelist creator
"""

# Typically ignore this.
# pylint: disable=invalid-name

# Disable these because this is our standard setup
# pylint: disable=wildcard-import,unused-wildcard-import,wrong-import-position

import os, sys

CIMEROOT = os.environ.get("CIMEROOT")
if CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")
sys.path.append(os.path.join(CIMEROOT, "scripts", "Tools"))

from standard_script_setup import *
from CIME.case import Case
from CIME.utils import expect
from CIME.buildnml import create_namelist_infile, parse_input
from CIME.utils import run_cmd, safe_copy
from CIME.nmlgen import NamelistGenerator

logger = logging.getLogger(__name__)

# pylint: disable=too-many-arguments,too-many-locals,too-many-branches,too-many-statements
####################################################################################
def _create_namelists(case, confdir, inst_string, infile, nmlgen, data_list_path):
####################################################################################
    """Write out the namelist for this component.

    Most arguments are the same as those for `NamelistGenerator`. The
    `inst_string` argument is used as a suffix to distinguish files for
    different instances. The `confdir` argument is used to specify the directory
    in which output files will be placed.
    """
    #----------------------------------------------------
    # Create config dictionary
    #----------------------------------------------------
    config = {}
    config['ocn_grid'] = case.get_value("OCN_GRID")
    nmlgen.init_defaults([infile], config)

    #----------------------------------------------------
    # Write output files
    #----------------------------------------------------
    namelist_file = os.path.join(confdir, "ocn_in")
    #----------------------------------------------------
    # Standard fortran namelists
    #----------------------------------------------------
    nmlgen.write_output_file(namelist_file, data_list_path, groups=['ocn_io', 'ocn_timemgr'])

    #----------------------------------------------------
    # Non-Standard Roms name value pairs list
    #----------------------------------------------------
    namelist_file = os.path.join(confdir, "ocean.in")

    nmlgen.write_output_file(namelist_file, data_list_path, groups=['ocean.in3','ocean.in2', 'ocean.in1'], format_="roms")

    # set rundir
    rundir = case.get_value("RUNDIR")

    # copy nuopc.runconfig to rundir
    safe_copy(os.path.join(confdir,"ocn_in"), rundir)
    safe_copy(os.path.join(confdir,"ocean.in"), rundir)


# pylint: disable=too-many-arguments,too-many-locals,too-many-branches,too-many-statements
###############################################################################
def buildnml(case, caseroot, compname):
###############################################################################
    """Build the roms namelist """

    # Build the component namelist
    if compname != "roms":
        raise AttributeError

    srcroot = case.get_value("SRCROOT")
    continue_run = case.get_value("CONTINUE_RUN")
    ninst = case.get_value("NINST_OCN")
    ocn_grid = case.get_value("OCN_GRID")  # BK: need a ocn grid var for roms

    rundir = case.get_value("RUNDIR")
    startdate = case.get_value("RUN_STARTDATE")
    starttod = case.get_value("START_TOD")
    dinlocroot = case.get_value("DIN_LOC_ROOT")
    ntasks = case.get_value("NTASKS_OCN")
    srcmodsdir = os.path.join(caseroot,"SourceMods","src.roms")
    confdir = os.path.join(caseroot,"Buildconf","romsconf")

    for _dir in (confdir, rundir, srcmodsdir):
        if not os.path.isdir(_dir):
            os.makedirs(_dir)


    # assume the domain descript nc file is under dinlocroot/share/domains
    ddomain = os.path.join(dinlocroot,"share","domains")


    #----------------------------------------------------
    # Construct the namelist generator
    #----------------------------------------------------
    # Determine directory for user modified namelist_definitions.xml and namelist_defaults.xml
    user_xml_dir = os.path.join(caseroot, "SourceMods", "src.roms")
    expect(os.path.isdir(user_xml_dir),
           "user_xml_dir %s does not exist "%user_xml_dir)

    # NOTE: User definition *replaces* existing definition.
    namelist_xml_dir = os.path.join(srcroot, "components", "roms", "cime_config")
    definition_file = [os.path.join(namelist_xml_dir, "namelist_definition_roms.xml")]
    user_definition = os.path.join(user_xml_dir, "namelist_definition_roms.xml")
    if os.path.isfile(user_definition):
        definition_file = [user_definition]
    for file_ in definition_file:
        expect(os.path.isfile(file_), "Namelist XML file %s not found!" % file_)

    # Create the namelist generator object - independent of instance
    nmlgen = NamelistGenerator(case, definition_file)

    #----------------------------------------------------
    # Clear out old data.
    #----------------------------------------------------
    data_list_path = os.path.join(case.get_case_root(), "Buildconf", "roms.input_data_list")
    if os.path.exists(data_list_path):
        os.remove(data_list_path)

    #----------------------------------------------------
    # Loop over instances
    #----------------------------------------------------
    for inst_counter in range(1, ninst+1):

        # determine instance string
        inst_string = ""
        if ninst > 1:
            inst_string = '_' + '%04d' % inst_counter

        # create namelist_infile using user_nl_file as input
        user_nl_file = os.path.join(caseroot, "user_nl_roms" + inst_string)
        expect(os.path.isfile(user_nl_file),
               "Missing required user_nl_file %s " %(user_nl_file))
        namelist_infile = os.path.join(confdir, "namelist_infile")
        create_namelist_infile(case, user_nl_file, namelist_infile)

        # create namelist and stream file(s) data component
        _create_namelists(case, confdir, inst_string, namelist_infile, nmlgen, data_list_path)

        # ------------------------------------------------------------------------------
        # call build-namelist - output will go in caseroot/Buildconf/romsconf/ocn_in
        # ------------------------------------------------------------------------------
        # determine the directory containing build-namelist script
        # first check to see if build-namelist exists in SourceMods, if it exists use it
        bldnml_dir = os.path.join(srcroot,"components","roms","bld")

    # now call build-namelist
    cmd = os.path.join(bldnml_dir, "roms.buildnml.csh")
    command = "%s -ntasks %s -continue %s -startdate %s -starttod %s -ocngrid %s -coderoot %s \
    -rundir %s -dinlocroot %s -domfile %s" \
    % (cmd, ntasks, continue_run, startdate, starttod, ocn_grid, srcroot, \
       rundir, dinlocroot, ddomain)
    if inst_string:
        command = command + " -inst_string {}".format(inst_string)

#    rc, out, err = run_cmd(command, from_dir=confdir)
#    expect(rc==0,"Command %s failed rc=%d\nout=%s\nerr=%s"%(cmd,rc,out,err))
#    if out is not None:
#        logger.debug("     %s"%out)
#    if err is not None:
#        logger.debug("     %s"%err)

    # copy pop namelist files from confdir to rundir
    #if os.path.isdir(rundir):
    #    file_src  = os.path.join(confdir, "wrf_in")
    #    file_dest = os.path.join(rundir, "wrf_in")
    #    shutil.copy(file_src, file_dest)


###############################################################################
def _main_func():
    caseroot = parse_input(sys.argv)
    with Case(caseroot) as case:
        buildnml(case, caseroot, "roms")

if __name__ == "__main__":
    _main_func()
